// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/acid/acid.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserResponse_Status int32

const (
	RegisterUserResponse_SUCCESS RegisterUserResponse_Status = 0
	RegisterUserResponse_FAILURE RegisterUserResponse_Status = 1
)

// Enum value maps for RegisterUserResponse_Status.
var (
	RegisterUserResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
	}
	RegisterUserResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
	}
)

func (x RegisterUserResponse_Status) Enum() *RegisterUserResponse_Status {
	p := new(RegisterUserResponse_Status)
	*p = x
	return p
}

func (x RegisterUserResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterUserResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_acid_acid_proto_enumTypes[0].Descriptor()
}

func (RegisterUserResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_acid_acid_proto_enumTypes[0]
}

func (x RegisterUserResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterUserResponse_Status.Descriptor instead.
func (RegisterUserResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_acid_acid_proto_rawDescGZIP(), []int{1, 0}
}

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_proto_acid_acid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acid_acid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_acid_acid_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Response      RegisterUserResponse_Status `protobuf:"varint,3,opt,name=response,proto3,enum=acid.RegisterUserResponse_Status" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_proto_acid_acid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acid_acid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_acid_acid_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserResponse) GetResponse() RegisterUserResponse_Status {
	if x != nil {
		return x.Response
	}
	return RegisterUserResponse_SUCCESS
}

type FetchUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchUserRequest) Reset() {
	*x = FetchUserRequest{}
	mi := &file_proto_acid_acid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchUserRequest) ProtoMessage() {}

func (x *FetchUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acid_acid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchUserRequest.ProtoReflect.Descriptor instead.
func (*FetchUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_acid_acid_proto_rawDescGZIP(), []int{2}
}

func (x *FetchUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type FetchUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchUserResponse) Reset() {
	*x = FetchUserResponse{}
	mi := &file_proto_acid_acid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchUserResponse) ProtoMessage() {}

func (x *FetchUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acid_acid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchUserResponse.ProtoReflect.Descriptor instead.
func (*FetchUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_acid_acid_proto_rawDescGZIP(), []int{3}
}

func (x *FetchUserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FetchUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_proto_acid_acid_proto protoreflect.FileDescriptor

const file_proto_acid_acid_proto_rawDesc = "" +
	"\n" +
	"\x15proto/acid/acid.proto\x12\x04acid\"?\n" +
	"\x13RegisterUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"y\n" +
	"\x14RegisterUserResponse\x12=\n" +
	"\bresponse\x18\x03 \x01(\x0e2!.acid.RegisterUserResponse.StatusR\bresponse\"\"\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\v\n" +
	"\aFAILURE\x10\x01\"(\n" +
	"\x10FetchUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"=\n" +
	"\x11FetchUserResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email2\x89\x01\n" +
	"\x04Acid\x12C\n" +
	"\n" +
	"createUser\x12\x19.acid.RegisterUserRequest\x1a\x1a.acid.RegisterUserResponse\x12<\n" +
	"\tfetchUser\x12\x16.acid.FetchUserRequest\x1a\x17.acid.FetchUserResponseB\x03Z\x01.b\x06proto3"

var (
	file_proto_acid_acid_proto_rawDescOnce sync.Once
	file_proto_acid_acid_proto_rawDescData []byte
)

func file_proto_acid_acid_proto_rawDescGZIP() []byte {
	file_proto_acid_acid_proto_rawDescOnce.Do(func() {
		file_proto_acid_acid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_acid_acid_proto_rawDesc), len(file_proto_acid_acid_proto_rawDesc)))
	})
	return file_proto_acid_acid_proto_rawDescData
}

var file_proto_acid_acid_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_acid_acid_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_acid_acid_proto_goTypes = []any{
	(RegisterUserResponse_Status)(0), // 0: acid.RegisterUserResponse.Status
	(*RegisterUserRequest)(nil),      // 1: acid.RegisterUserRequest
	(*RegisterUserResponse)(nil),     // 2: acid.RegisterUserResponse
	(*FetchUserRequest)(nil),         // 3: acid.FetchUserRequest
	(*FetchUserResponse)(nil),        // 4: acid.FetchUserResponse
}
var file_proto_acid_acid_proto_depIdxs = []int32{
	0, // 0: acid.RegisterUserResponse.response:type_name -> acid.RegisterUserResponse.Status
	1, // 1: acid.Acid.createUser:input_type -> acid.RegisterUserRequest
	3, // 2: acid.Acid.fetchUser:input_type -> acid.FetchUserRequest
	2, // 3: acid.Acid.createUser:output_type -> acid.RegisterUserResponse
	4, // 4: acid.Acid.fetchUser:output_type -> acid.FetchUserResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_acid_acid_proto_init() }
func file_proto_acid_acid_proto_init() {
	if File_proto_acid_acid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_acid_acid_proto_rawDesc), len(file_proto_acid_acid_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_acid_acid_proto_goTypes,
		DependencyIndexes: file_proto_acid_acid_proto_depIdxs,
		EnumInfos:         file_proto_acid_acid_proto_enumTypes,
		MessageInfos:      file_proto_acid_acid_proto_msgTypes,
	}.Build()
	File_proto_acid_acid_proto = out.File
	file_proto_acid_acid_proto_goTypes = nil
	file_proto_acid_acid_proto_depIdxs = nil
}
